#!/bin/bash

mkdir -p $HOME/scripts
chmod 777 $PWD/scripts -R

for file in $PWD/scripts/*; do 
	ln -sf $file $HOME/scripts/
done

chmod u+x $HOME/scripts/ -R

ln -sf $PWD/.bashrc $HOME/.bashrc
ln -sf $PWD/.bash_aliases $HOME/.bash_aliases
ln -sf $PWD/.bash_profile $HOME/.bash_profile
ln -sf $PWD/.zshrc $HOME/.zshrc
ln -sf $PWD/.vimrc $HOME/.vimrc
ln -sf $PWD/.tmux.conf $HOME/.tmux.conf

ln -sf $PWD/.gitconfig $HOME/.gitconfig

mkdir -p $HOME/wallpapers
for file in $PWD/wallpapers/*; do 
  ln -sf $file $HOME/wallpapers/
done

for i in pulseaudio udev rofi i3 nvim alacritty zathura xorg libinput ranger compton mpd systemd; do
	cd $i && ./setup
	cd "$OLDPWD"
done
