#!/bin/sh


if [ $button == 1 ]
then
  playerctl previous
elif [ $button == 3 ]
then
  playerctl next
elif [ $button == 2 ]
then
  playerctl play-pause
fi

sleep 0.5
echo $(playerctl metadata xesam:artist) - $(playerctl metadata xesam:title)

