#!/usr/bin/sh

STATUS=$(acpi)
FULLTEXT=$null


# ICONS
UNPLUGGED_ICON=$(printf '\uf00d\uf240')

color() {
    if [[ $1 -lt 20 ]]; then
        echo 'red'
    elif [[ $1 -lt 50 ]]; then
        echo 'yellow'
    else
        echo 'white'
    fi
}

icon() {
    case $1 in 
        "Full")
            echo "<span font='FontAwesome'>$(printf '\uf1e6')</span>"
            ;;
        "Discharging")
            echo "<span font='FontAwesome'>$(printf '\uf240')</span>"
            ;;
        "Unknown")
            echo "<span font='FontAwesome'>$(printf '\uf128\uf240')</span>"
            ;;
        *)
            echo "<span color='yellow' font='FontAwesome'>$(printf '\uf0e7\uf1e6')</span>"
            ;;
    esac
}

if [[ -z $STATUS ]]; then
    # BATTERY UNPLUGGED
    FULLTEXT="<span color='red' font='FontAwesome'>${UNPLUGGED_ICON}</span>"
else
    TEXT=$(acpi | awk -F'[, ]+' '{print $4}')

    PERCENT_REMAINING=$(echo $STATUS | awk -F'[, ]+' '{print $4}' | sed 's/%//') 
    STATE=$(echo $STATUS | awk -F'[, ]+' '{print $3}')
    
    if [[ $PERCENT_REMAINING -gt 50 ]]
    then
        FULLTEXT="$(icon ${STATE})<span font='FontAwesome'>${TEXT}</span>"
    else
        FULLTEXT="$(icon ${STATE})<span color='$(color $PERCENT_REMAINING)' font='FontAwesome'>${TEXT}</span>"
    fi

fi

echo $FULLTEXT
